stages:
  - preflight
  - homeassistant
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Generic preflight template
.preflight: &preflight
  stage: preflight
  tags:
    - hass

# Generic Home Assistant template
.ha: &ha
  stage: homeassistant
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  before_script:
    - python -m homeassistant --version
    - cp $CI_PROJECT_DIR/ci_secrets.yaml $CI_PROJECT_DIR/secrets.yaml
    - rm -f packages/hacs.yaml
    - rm -f packages/rubbish.yaml
  script:
    - |
        /usr/local/bin/python -m homeassistant \
          --config $CI_PROJECT_DIR/ \
          --script check_config
    - |
        if /usr/local/bin/python -m homeassistant \
          --config $CI_PROJECT_DIR/ --script check_config | \
          grep "ERROR" ; then exit 1; else echo "No YAML errors"; fi

  tags:
    - hass

# before_script:
#  - apt-get update
#  - apt-get install -y mosquitto-clients

# Preflight jobs
shellcheck:
  <<: *preflight
  image:
    name: koalaman/shellcheck-alpine:stable
    entrypoint: [""]
  before_script:
    - ln -s $CI_PROJECT_DIR /config
    - mv shell_commands/ci_secrets.sh shell_commands/secrets.sh
    - shellcheck --version
    - apk --no-cache add grep
  script:
    - |
      for file in $(grep -IRl "#\!\(/usr/bin/env bash\|/bin/bash\)" \
      --exclude-dir ".git" .); do
        if ! shellcheck -x $file; then
          export FAILED=1
        else
          echo "$file OK"
        fi
      done
      if [ "${FAILED}" = "1" ]; then
        exit 1
      fi

yamllint:
  <<: *preflight
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
    - mv ci_secrets.yaml secrets.yaml
    - rm -f known_devices.yaml appdaemon.yaml apps/apps.yaml
  script:
    - yamllint .
  allow_failure: true

jsonlint:
  <<: *preflight
  image: sahsu/docker-jsonlint
  before_script:
    - jsonlint --version || true
  script:
    - |
      for file in $(find . -type f -name \
      "*.json" -path "mysensors.json" -prune); do
        if ! jsonlint -q $file; then
          export FAILED=1
        else
          echo "$file OK"
        fi
      done
      if [ "${FAILED}" = "1" ]; then
        exit 1
      fi

markdownlint:
  <<: *preflight
  image:
    name: ruby:alpine
    entrypoint: [""]
  before_script:
    - apk --no-cache add git
    - gem install mdl
    - mdl --version
  script:
    - mdl --style ci_config/mdstyle.rb --warnings --git-recurse .

# Home Assistant test jobs
ha-latest:
  <<: *ha
  image:
    name: homeassistant/home-assistant:latest
    entrypoint: [""]

ha-rc:
  <<: *ha
  image:
    name: homeassistant/home-assistant:rc
    entrypoint: [""]
  allow_failure: true

ha-dev:
  <<: *ha
  image:
    name: homeassistant/home-assistant:dev
    entrypoint: [""]
  allow_failure: true

deploy:
  stage: deploy
  image:
    name: alpine:latest
    entrypoint: [""]
  environment:
    name: home-assistant
  before_script:
    - apk --no-cache add curl
  script:
    - "curl -X POST -H \"Authorization: Bearer $DEPLOYMENT_HASS_TOKEN\" -H \
      \"Content-Type: application/json\" \
      $DEPLOYMENT_HASS_URL/api/services/script/configuation_update"
  only:
    refs:
      - master
  tags:
    - hass
