# @Author: Will Scott <willscottuk>
# @Date:   11/06/2017 18:10
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 08/09/2018 14:54


homeassistant:

  # Name of the location where Home Assistant is running
  name: Cronx

  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long

  # Impacts weather/sunrise data
  elevation: !secret elev

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  # Global customisations
  customize_glob: !include config/customize_glob.yaml

  # Most of the configuration is split into thematic packages
  packages: !include_dir_named packages

sun:
zeroconf:
config:
map:
alexa:
ffmpeg:
system_health:
mobile_app:

frontend: !include config/frontend.yaml
history: !include config/history.yaml
script: !include_dir_named scripts
python_script:
updater: !include config/updater.yaml
recorder: !include config/recorder.yaml
logger: !include config/logger.yaml
zwave: !include config/zwave.yaml
http: !include config/http.yaml
discovery: !include config/discovery.yaml
logbook: !include config/logbook.yaml
canary: !include config/canary.yaml
mqtt: !include config/mqtt.yaml
# emulated_hue: !include config/emulated_hue.yaml
ios: !include config/ios.yaml
cloud: !include config/cloud.yaml
homekit: !include config/homekit.yaml
influxdb: !include config/influxdb.yaml
xiaomi_aqara: !include config/xiaomi.yaml
ifttt: !include config/ifttt.yaml
custom_updater: !include config/custom_updater.yaml