# @Author: Will Scott <willscott>
# @Date:   20/01/2018 12:56
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 20/01/2018 12:56

username: !secret canary_user
password: !secret canary_pass
