# @Author: Will Scott <willscott>
# @Date:   20/01/2018 12:49
# @Project: Ambassadr Home Automation
# @Last modified by:   willscott
# @Last modified time: 24/03/2018 18:26

exclude:
  entities:
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_summary
    - sensor.dark_sky_daily_high_temperature
    - sensor.front_door_access_control
    - sensor.time
    - sensor.eastbound_trams
    - sensor.westbound_trams
  domains:
    - group
    - automation
    - zone
    - history_graph
    - zwave
    - script
